In [6]:
import numpy as np
import pandas as pd
idx = pd.IndexSlice
import xarray as xr

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path
from itertools import product

from scipy.stats import linregress

import sys
sys.path.append('../../funcs')
sys.path.append('../../constants')
from taus import decorrelation_temporal_model, fit_coh_decay_model
from xarray_tools import find_cor_ts
from colors import loc_colors

In [3]:
dss = {fp.stem.split('_')[0]: xr.open_dataset(fp) for fp in sorted(list(Path('/Users/rdcrlzh1/Documents/uavsar-coherence/uavsar').glob('*_tau.nc'))) if 'lowman' not in fp.stem}

home_dir = Path('/Users/rdcrlzh1/Documents/uavsar-coherence')
fig_dir = home_dir.joinpath('figures', 'non-snow')

In [9]:
for stem, ds in dss.items():
    print(stem)
    print(ds.heading)

dorado
<xarray.DataArray 'heading' (heading: 1)>
array([340])
Coordinates:
  * heading      (heading) int64 340
    spatial_ref  int64 ...
grmesa
<xarray.DataArray 'heading' (heading: 1)>
array([274])
Coordinates:
  * heading      (heading) int64 274
    spatial_ref  int64 ...
rockmt
<xarray.DataArray 'heading' (heading: 2)>
array([141, 321])
Coordinates:
  * heading      (heading) int64 141 321
    spatial_ref  int64 ...
sierra
<xarray.DataArray 'heading' (heading: 2)>
array([173, 354])
Coordinates:
  * heading      (heading) int64 173 354
    spatial_ref  int64 ...
silver
<xarray.DataArray 'heading' (heading: 1)>
array([347])
Coordinates:
  * heading      (heading) int64 347
    spatial_ref  int64 ...
stlake
<xarray.DataArray 'heading' (heading: 2)>
array([ 91, 271])
Coordinates:
  * heading      (heading) int64 91 271
    spatial_ref  int64 ...


In [8]:
res = pd.DataFrame(index = pd.MultiIndex(levels = [[], [], []], codes = [[], [],[]], names = ['site', 'dt', 'pol']), columns = ['25', '50', '75'])

lc_dic = {'water': [11,11], 'developed': [21,24], 'forest': [41, 43], 'shrub': [51, 52], 'herbaceous': [71, 74]}

for stem, ds in dss.items():
    ts = find_cor_ts(ds)

    for heading, t1, t2 in ts:
        print(heading)
    # ds['curvefit_coefficients'].sel(param = 'tau', pol = 'VV').plot(vmax = 30)
    # plt.gca().set_title(stem)
    # plt.show()

340
340
340
340
274
274
274
274
274
274
274
274
274
274


KeyboardInterrupt: 